#!/bin/sh
set -u

root=$(CDPATH= cd -- "$(git rev-parse --show-toplevel)" && pwd)

package_arch() {
    REPO_DB="/var/lib/pacman-local/pacman-local.db.tar.gz"
    REPO_PATH="$(dirname "$REPO_DB")"

    TMP_DIR="$(mktemp -d)"
    export PKGDEST="$TMP_DIR"
    cd "$root"/contrib/arch || exit 1
    makepkg -s

    if [ -d "$REPO_PATH" ]; then
        for pkg in "$PKGDEST"/*.pkg.tar.zst; do
            mv "$pkg" "$REPO_PATH/"
            repo-add "$REPO_DB" "$REPO_PATH/$(basename "$pkg")"
        done
        git restore PKGBUILD
    fi
}

if grep -q ID=arch /etc/os-release > /dev/null 2>&1 ; then
    package_arch
fi
